"""HPC3 process files live in the SHARED AiScientist root and get swept after 3 days.

Two properties this file exists to pin down, because getting either wrong is expensive:

1. **Nothing generated by a run lands in a member's personal HPC3 dir any more.** Every run
   workspace, Slurm script and job log resolves under ``<shared_root>/Temp/<user>/`` — which is
   what makes an automatic sweep safe at all (there is nothing hand-curated in there to lose).
2. **The sweeper's blast radius is exactly that dir.** Raw uploads, the synced source, another
   member's Temp, and every personal lab dir must stay out of reach — of the script's own
   arguments AND of the storage panel's delete guard.

The sweep's *semantics* (a unit is deleted only when its whole subtree is cold) live in
``deploy/hpc3/aiscientist_temp_gc.sh`` and are exercised against a real tree here too, on the
platforms that have GNU find; the Python side is only responsible for calling it correctly.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
import time
import types
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from bioagent.gateway import hpc_gc  # noqa: E402
from bioagent.gateway.executor import ExecResult  # noqa: E402
from bioagent.gateway.settings import HPCSettings  # noqa: E402

GC_SCRIPT = Path(__file__).resolve().parents[1] / "deploy" / "hpc3" / "aiscientist_temp_gc.sh"


class _FakeRemote:
    """Records commands; answers ``test -d`` however the test wants."""

    def __init__(self, *, root_exists: bool = True, fail: str = "") -> None:
        self.username = "tester"
        self.commands: list[str] = []
        self.staged: list[tuple[str, str]] = []
        self.root_exists = root_exists
        self.fail = fail
        self.stdout = "GC_RESULT removed=4 kept=1"

    def exec(self, command: str, timeout: float = 60.0) -> ExecResult:
        self.commands.append(command)
        if command.startswith("test -d") and not self.root_exists:
            return ExecResult(command=command, exit_status=1, stdout="", stderr="")
        if self.fail and self.fail in command:
            return ExecResult(command=command, exit_status=1, stdout="", stderr="boom")
        if command.startswith("sbatch"):
            return ExecResult(command=command, exit_status=0, stdout="7654321", stderr="")
        if command.startswith("tail"):          # the previous sweep's log
            return ExecResult(command=command, exit_status=0, stdout=self.stdout, stderr="")
        return ExecResult(command=command, exit_status=0, stdout="", stderr="")

    def put_file(self, local: str, remote: str) -> None:
        self.staged.append((local, remote))


# --------------------------------------------------------------------------- settings

def test_shared_root_and_ttl_have_the_documented_defaults():
    st = HPCSettings()
    assert st.shared_root == "/dfs3b/ruic20_lab/software/AiScientist"
    assert st.temp_ttl_days == 3


def test_shared_root_and_ttl_come_from_env(monkeypatch):
    monkeypatch.setenv("BIOAGENT_HPC_SHARED_ROOT", "/dfs3b/ruic20_lab/elsewhere/AiScientist/")
    monkeypatch.setenv("BIOAGENT_TEMP_TTL_DAYS", "7")
    st = HPCSettings.from_env()
    assert st.shared_root == "/dfs3b/ruic20_lab/elsewhere/AiScientist"   # trailing slash normalized
    assert st.temp_ttl_days == 7


# --------------------------------------------------------------------------- layout

def test_process_files_go_to_shared_temp_never_a_personal_dir():
    # gateway.app pulls in fastapi, which CI deliberately does not install (see
    # requirements-dev.txt) — skip like every other app-level test rather than erroring.
    pytest.importorskip("fastapi")
    from bioagent.gateway import app as gw_app

    conn = types.SimpleNamespace(
        executor=types.SimpleNamespace(username="tester"), owner="tester",
        settings=HPCSettings())

    temp = gw_app._temp_base(conn)
    assert temp == "/dfs3b/ruic20_lab/software/AiScientist/Temp/tester"
    # The legacy personal dir is still addressable (for browsing) but is not a prefix of Temp.
    assert not temp.startswith(gw_app._storage_base(conn) + "/")

    # Raw data and the synced source are deliberately OUTSIDE Temp — the sweeper must never
    # be able to walk into either.
    assert not gw_app._hpc_uploads_dir(conn).startswith(temp)
    assert gw_app._shared_dir(conn, "pysrc") == "/dfs3b/ruic20_lab/software/AiScientist/pysrc/tester"


def test_shared_paths_are_per_user():
    mine = hpc_gc.shared_paths("/dfs3b/ruic20_lab/software/AiScientist", "tester")
    theirs = hpc_gc.shared_paths("/dfs3b/ruic20_lab/software/AiScientist", "someoneelse")
    assert mine["temp"] == "/dfs3b/ruic20_lab/software/AiScientist/Temp/tester"
    # EVERY subdir is per-user, `bin` included: members stage the sweeper concurrently and one
    # shared copy would mean each overwriting a file the others own.
    assert mine["bin"] == "/dfs3b/ruic20_lab/software/AiScientist/bin/tester"
    for kind in ("temp", "uploads", "pysrc", "bin"):
        assert not theirs[kind].startswith(mine[kind])


# --------------------------------------------------------------------------- bootstrap

def test_missing_shared_root_is_reported_with_the_exact_fix():
    remote = _FakeRemote(root_exists=False)
    ok, message = hpc_gc.ensure_shared_dirs(remote, "/dfs3b/ruic20_lab/software/AiScientist", "tester")
    assert ok is False
    # /dfs3b/ruic20_lab is drwxr-s--- ruic20, so this one mkdir is a human prerequisite. The
    # message has to carry it, or every offloaded job later dies on an unexplained mkdir.
    assert "mkdir -p /dfs3b/ruic20_lab/software/AiScientist" in message
    assert "BIOAGENT_HPC_SHARED_ROOT" in message
    assert not any(c.startswith("umask") for c in remote.commands)   # nothing attempted


def test_bootstrap_creates_only_this_users_dirs_group_writable():
    remote = _FakeRemote()
    ok, _ = hpc_gc.ensure_shared_dirs(remote, "/dfs3b/ruic20_lab/software/AiScientist", "tester")
    assert ok is True
    mkdir = next(c for c in remote.commands if "mkdir -p" in c)
    for expected in ("/AiScientist/Temp/tester", "/AiScientist/uploads/tester",
                     "/AiScientist/pysrc/tester", "/AiScientist/bin/tester"):
        assert expected in mkdir
    assert "umask 002" in mkdir and hpc_gc.DIR_MODE in mkdir


# --------------------------------------------------------------------------- sweep call

def test_sweep_command_is_pinned_to_one_user_and_an_explicit_root_and_ttl():
    cmd = hpc_gc.sweep_command("/root/bin/temp_gc.sh", "/dfs3b/ruic20_lab/software/AiScientist/", 3, "tester")
    assert "--root /dfs3b/ruic20_lab/software/AiScientist " in cmd     # trailing slash stripped
    assert "--ttl-days 3" in cmd
    assert "--user tester" in cmd
    assert "--dry-run" not in cmd
    assert "--dry-run" in hpc_gc.sweep_command("/s.sh", "/r", 3, "tester", dry_run=True)


def test_a_hostile_username_cannot_smuggle_a_second_command():
    cmd = hpc_gc.sweep_command("/s.sh", "/r", 3, "tester; rm -rf /")
    assert "--user 'tester; rm -rf /'" in cmd    # quoted, so it is one argument the script rejects


def test_the_sweep_runs_on_a_compute_node_not_the_login_node():
    """RCIC's rule: login nodes are for logging in and SUBMITTING jobs. The sweep walks trees and
    calls rm -rf, so the only thing the login node may run is the sbatch."""
    remote = _FakeRemote()
    out = hpc_gc.sweep_temp(remote, "/dfs3b/ruic20_lab/software/AiScientist", "tester", 3,
                            partition="standard", account="ruic20_lab")
    assert out["status"] == "submitted" and out["job_id"] == "7654321"
    # the previous run's numbers, read back from its log
    assert out["removed"] == 4 and out["kept"] == 1
    assert out["root"] == "/dfs3b/ruic20_lab/software/AiScientist/Temp/tester"
    assert remote.staged and remote.staged[0][1].endswith("/AiScientist/bin/tester/temp_gc.sh")

    submit = next(c for c in remote.commands if c.startswith("sbatch"))
    assert "--partition=standard" in submit and "--account=ruic20_lab" in submit
    assert "--parsable" in submit and "temp_gc.log" in submit
    # the destructive part is INSIDE --wrap (i.e. inside the job), never run directly
    assert "--wrap" in submit and "temp_gc.sh" in submit
    assert not any(c.startswith("bash ") for c in remote.commands)


def test_submit_command_omits_the_account_flag_when_there_is_none():
    cmd = hpc_gc.submit_command("payload", "/log", "tester", partition="standard", account="")
    assert "--account" not in cmd and "--partition=standard" in cmd


def test_ttl_zero_disables_the_sweep_entirely():
    remote = _FakeRemote()
    assert hpc_gc.sweep_temp(remote, "/r", "tester", 0)["status"] == "disabled"
    assert remote.commands == [] and remote.staged == []


def test_a_failed_sweep_is_reported_not_raised():
    remote = _FakeRemote(fail="sbatch")
    out = hpc_gc.sweep_temp(remote, "/r", "tester", 3)
    assert out["status"] == "error" and "boom" in out["error"]


# --------------------------------------------------------------------------- delete guard

def test_storage_delete_guard_covers_the_new_roots_but_not_another_member():
    pytest.importorskip("fastapi")
    from bioagent.gateway import app as gw_app

    conn = types.SimpleNamespace(
        executor=types.SimpleNamespace(username="tester"), owner="tester",
        settings=HPCSettings())
    allowed = [p for _label, p in gw_app._storage_areas(conn)]

    def permitted(path: str) -> bool:
        return ".." not in path and any(path.startswith(a + "/") for a in allowed)

    assert permitted("/dfs3b/ruic20_lab/software/AiScientist/Temp/tester/analysis/abc")
    assert permitted("/dfs3b/ruic20_lab/software/AiScientist/uploads/tester/case.vcf.gz")
    assert permitted("/dfs3b/ruic20_lab/tester/old_run")            # legacy personal dir, by hand
    # Sharing one project root must NOT let a member reach anyone else's files.
    assert not permitted("/dfs3b/ruic20_lab/software/AiScientist/Temp/someoneelse/analysis/abc")
    assert not permitted("/dfs3b/ruic20_lab/someoneelse/data.h5ad")
    assert not permitted("/dfs3b/ruic20_lab/software/AiScientist/Temp/tester/../../someoneelse")
    # the shared root also holds 100+GB of containers/model weights — off limits to the panel
    assert not permitted("/dfs3b/ruic20_lab/software/AiScientist/containers/vllm.sif")
    assert not permitted("/dfs3b/ruic20_lab/software/reference")


# --------------------------------------------------------------------------- the script itself

def _gnu_find() -> bool:
    """The sweeper targets HPC3 (GNU findutils/coreutils). Skip on BSD userlands (macOS)."""
    try:
        out = subprocess.run(["find", "--version"], capture_output=True, text=True, timeout=10)
        ok_find = "GNU" in out.stdout
        out = subprocess.run(["touch", "-d", "-1 days", "/dev/null"], capture_output=True, timeout=10)
        return ok_find and out.returncode in (0, 1)
    except (OSError, subprocess.SubprocessError):
        return False


@pytest.mark.skipif(not _gnu_find(), reason="sweeper needs GNU find/touch (as on HPC3)")
def test_sweeper_removes_cold_units_and_never_touches_warm_ones_or_other_areas(tmp_path):
    root = tmp_path / "AiScientist"
    temp = root / "Temp" / "tester"
    for rel in ("analysis/coldrun/work", "analysis/warmrun/work", "variant/coldvar",
                "scratch/runcode"):
        (temp / rel).mkdir(parents=True)
        (temp / rel / "f.bin").write_text("x")
    (root / "uploads" / "tester").mkdir(parents=True)
    (root / "uploads" / "tester" / "patient.vcf.gz").write_text("raw")
    (root / "Temp" / "someoneelse" / "analysis" / "theirs").mkdir(parents=True)
    (root / "Temp" / "someoneelse" / "analysis" / "theirs" / "f.bin").write_text("x")

    old = time.time() - 10 * 86400
    for p in root.rglob("*"):
        os_utime(p, old)
    os_utime(root, old)
    # one fresh file deep inside warmrun — the whole run must survive because of it
    (temp / "analysis/warmrun/work/fresh.h5ad").write_text("new")

    subprocess.run(["bash", str(GC_SCRIPT), "--root", str(root), "--ttl-days", "3",
                    "--user", "tester", "--quiet"], check=True, capture_output=True, timeout=120)

    assert not (temp / "analysis/coldrun").exists()
    assert not (temp / "variant/coldvar").exists()
    assert not (temp / "scratch/runcode").exists()
    # kept: the warm run, INCLUDING its 10-day-old file — units are all-or-nothing, so an
    # in-flight job can never be half-deleted out from under itself.
    assert (temp / "analysis/warmrun/work/f.bin").exists()
    # never in scope
    assert (root / "uploads/tester/patient.vcf.gz").exists()
    assert (root / "Temp/someoneelse/analysis/theirs/f.bin").exists()

    shutil.rmtree(root)


def os_utime(path: Path, when: float) -> None:
    import os
    os.utime(path, (when, when))
