#!/usr/bin/env python3
"""Keep every ``tools/<name>/TOOL.md`` and the tool index ``tools/README.md`` in step with the code.

A TOOL.md mixes hand-written sections (what the tool is for, its outputs, its limits) with
generated ones. A generated section sits between two markers and is rewritten from the live tool::

    <!-- generated:parameters -->      the schema: every parameter, its type, default and meaning
    <!-- generated:runs-on -->         where it runs, from the manifest and the tool record
    <!-- generated:model-description -->  the description the model reads, verbatim

each closed by ``<!-- /generated:NAME -->``. ``tools/README.md`` is generated whole.

    python scripts/tool_docs.py            # rewrite what is stale
    python scripts/tool_docs.py --check    # exit 1 if anything is stale (tests/test_tool_docs.py)
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from aiscientist.tools import catalog  # noqa: E402

TOOLS = ROOT / "src" / "aiscientist" / "tools"

RUNS_ON_TEXT = {
    "inprocess": "In the gateway process; it returns in seconds and needs no HPC3 job.",
    "hpc:analysis": (
        "As a Slurm CPU job inside `analysis.sif` on HPC3, through the analysis line's job entry "
        "point `python -m aiscientist.tools.scrna_cli`, reading and writing the run's `work/` and "
        "`artifacts/` on dfs3b. When the session has no HPC3 executor it runs in the gateway process."),
    "hpc:variant": (
        "As a Slurm job inside `vep.sif` on HPC3 (offline VEP with a local cache), through "
        "`python -m aiscientist.tools.variant_cli`. Small VCFs, or a session without HPC3, use the "
        "Ensembl REST API from the gateway instead (capped at a few hundred variants)."),
    "hpc:phenotype": (
        "As a Slurm job inside `lirical.sif` on HPC3, through `python -m aiscientist.tools.phenotype_cli`. "
        "Without HPC3 it returns `not_installed` rather than a guess."),
    "hpc:literature": (
        "As a Slurm job inside `paperqa.sif` on HPC3 (the PubMedBERT index lives on dfs3b), through "
        "`python -m aiscientist.tools.paperqa_cli`, calling the session's served model. It is left out "
        "of the catalog when the session has no GPU allocation."),
    "gpu:scgpt": (
        "As a GPU Slurm job inside `scgpt.sif`, through the runner the gateway injects "
        "(`gateway/scgpt_runner.py`). Without a GPU session it stays listed but reports that it is "
        "not enabled."),
}

INDEX_HEAD = """# Tools

Every model-callable domain tool lives in its own folder here. This file is generated by
`scripts/tool_docs.py` from the folders' `TOOL.md` manifests; edit those, not this table.

| Tool | What it does | Category | Runs on | Line |
|---|---|---|---|---|
"""

INDEX_TAIL = """
## Anatomy of a tool folder

```
<tool>/
  TOOL.md      front matter = the manifest the platform reads; body = this tool's documentation
  tool.py      the factory (make_tool or the name in `entry:`) and the executor
  __init__.py  docstring only: import names from the module that defines them
```

Shared code: `_lib/` (helpers more than one tool of a line uses; private to this package),
`genesets/` and `gene_panels/` (reference data), `datasets.py` (the dataset profile, also run as the
analysis line's `preflight` step), `run_deps.py` (per-run dependency installs inside a job).
Contract and doors: `sdk.py` (the tool record and context), `catalog.py` (discovery from
`TOOL.md`), `api.py` (everything else the platform may use). Job entry points, one per HPC3
image: `scrna_cli.py`, `variant_cli.py`, `phenotype_cli.py`, `paperqa_cli.py`.

## Adding a tool

1. Create `<name>/` with a `tool.py` whose factory returns a `HarnessTool` named `<name>`.
2. Add `<name>/TOOL.md`: the front matter fields are documented in `catalog.py`; copy the section
   layout of an existing tool, leave the `generated` markers empty.
3. Run `python scripts/tool_docs.py`, then the tests. No platform file changes: the registry, the
   HPC3 routing, the fast-chat selection and the System page all read the manifest.
4. Import only `aiscientist.tools.sdk` (and other tools' public names) from tool code; the platform
   is off limits (`tests/test_repo_boundaries.py`).
"""


def _cell(text: str) -> str:
    return " ".join(str(text).split()).replace("|", "\\|")


def parameters_md(tool) -> str:
    props = (tool.parameters or {}).get("properties") or {}
    required = set((tool.parameters or {}).get("required") or [])
    if not props:
        return "This tool takes no parameters."
    rows = ["| Parameter | Type | Default | Meaning |", "|---|---|---|---|"]
    for name, spec in props.items():
        spec = spec if isinstance(spec, dict) else {}
        typ = spec.get("type", "")
        if typ == "array":
            typ = f"array of {spec.get('items', {}).get('type', 'any')}"
        if "enum" in spec:
            typ += " (" + ", ".join(f"`{v}`" for v in spec["enum"]) + ")"
        if name in required:
            default = "required"
        elif "default" in spec:
            default = f"`{spec['default']!r}`" if spec["default"] != "" else "`''`"
        else:
            default = "—"
        rows.append(f"| `{name}` | {_cell(typ)} | {default} | {_cell(spec.get('description', ''))} |")
    return "\n".join(rows)


def runs_on_md(m, tool) -> str:
    lines = [RUNS_ON_TEXT[m.runs_on]]
    if m.image:
        lines[0] = lines[0].replace(" inside `analysis.sif`", "")
        how = ("built on first use from conda-forge + bioconda (" + m.image.split(":", 1)[1] + ")"
               if m.image.startswith("bioconda:") else "pulled on first use")
        lines.append(f"Its job runs in its OWN image instead of the line's: `{m.image}`, {how} into "
                     "the shared containers directory on HPC3 and reused by every later run.")
    resources = [f"{m.cpus} CPUs" if m.cpus else "", f"{m.mem_gb} GB" if m.mem_gb else "",
                 f"up to {m.time_limit}" if m.time_limit else ""]
    if any(resources):
        lines.append("Slurm resources for its job: " + ", ".join(r for r in resources if r) + ".")
    if tool.requires:
        lines.append("Needs: " + ", ".join(f"`{r}`" for r in tool.requires) + ".")
    lines.append("Reads private data: " + ("yes; its results stay inside the run." if tool.reads_private_data
                                          else "no."))
    lines.append("On the fast chat path: " + ("yes." if m.chat else "no (research runs only)."))
    return "\n\n".join(lines)


def model_description_md(tool) -> str:
    return "\n".join("> " + ln if ln else ">" for ln in _wrap(tool.description).splitlines())


def _wrap(text: str, width: int = 98) -> str:
    import textwrap
    return textwrap.fill(" ".join(text.split()), width=width - 2)


def fill(text: str, name: str, content: str) -> str:
    pat = re.compile(rf"(<!-- generated:{name} -->\n)(.*?)(<!-- /generated:{name} -->)", re.S)
    if not pat.search(text):
        raise SystemExit(f"missing <!-- generated:{name} --> block")
    return pat.sub(lambda mm: mm.group(1) + content.rstrip("\n") + "\n" + mm.group(3), text)


def render_tool_md(m) -> str:
    tool = catalog.build(m)
    text = (m.folder / "TOOL.md").read_text(encoding="utf-8")
    text = fill(text, "parameters", parameters_md(tool))
    text = fill(text, "runs-on", runs_on_md(m, tool))
    text = fill(text, "model-description", model_description_md(tool))
    return text


def render_index() -> str:
    rows = []
    for m in catalog.manifests():
        rows.append(f"| [`{m.name}`]({m.name}/TOOL.md) | {_cell(m.summary)} | {m.category} | "
                    f"`{m.runs_on}` | {m.line or '—'} |")
    return INDEX_HEAD + "\n".join(rows) + "\n" + INDEX_TAIL


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="report stale files and exit 1 instead of writing")
    a = ap.parse_args(argv)
    catalog.manifests.cache_clear()
    targets = {m.folder / "TOOL.md": render_tool_md(m) for m in catalog.manifests()}
    targets[TOOLS / "README.md"] = render_index()
    stale = [p for p, txt in targets.items() if not p.exists() or p.read_text(encoding="utf-8") != txt]
    if a.check:
        for p in stale:
            print(f"stale: {p.relative_to(ROOT)}")
        return 1 if stale else 0
    for p in stale:
        p.write_text(targets[p], encoding="utf-8")
        print(f"wrote {p.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
